##
## - collada_joint_name : euslisp_joint_name (start with :)
##

rarm:
  - joint1   : rarm-joint1
  - joint2   : rarm-joint2
  - joint3   : rarm-joint3
  - joint4   : rarm-joint4

## end-coords
rarm-end-coords:
  parent : end_effector_link

## reset-pose
angle-vector:
  reset-pose : [0.0, -67.61, 35.52, 32.54]

